### ISSUE TITLE
Method to customize document identifiers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-generic#22]
Users who use this gem will want to customize their document identifiers. Let's use the ISO document identifier scheme as an example to adapt for.

The ISO document identifier scheme differs by stage:

Template for unpublished:
* `ISO {stage} {report number}[-{part number}]:{year}`

Template for published:
* `ISO {stage} {report number}[-{part number}]:{year}`

Examples:
* ISO CD XXXX–2 (“Committee Draft of ISO XXXX Part 2”);
* ISO YYYY-3:2020 (“ISO YYYY Part 3, 2020 edition”).

Template for unpublished amendments:
* `ISO {stage} {report number}[-{part number}]:{year}/{“Cor”|“Amd”} {number}:{year}`

For example:
* ISO/IEC 14888-2:2008/Cor 1:2015 (“First correction—issued in 2015—to ISO/IEC 14888 Part 2, 2008 edition”);
* ISO/IEC 18031:2011/Amd 1:2017 (“First amendment—issued in 2017—to ISO/IEC 18031, 2011 edition”)

We can use a YAML structure to express this.

If it is simple:
```yaml
docid_scheme: "{orgid} {docnumber}"
```

If more complex:
```yaml
docid_scheme:
  - doctype: [ standard, technical-report ]
    stages:
       published: "ISO {report number}[-{part number}]:{year}"
       working-draft: "ISO {stage} {report number}[-{part number}]:{year}"
       committee-draft: "ISO {stage} {report number}[-{part number}]:{year}"
    ...
  - doctype: [ amendment ]
    stages:
      published: "ISO {report number}[-{part number}]:{year}/{“Cor”|“Amd”} {number}:{year}"
      working-draft: "ISO {stage} {report number}[-{part number}]:{year}/{“Cor”|“Amd”} {number}:{year}"
      committee-draft: "ISO {stage} {report number}[-{part number}]:{year}/{“Cor”|“Amd”} {number}:{year}"
    ...
```

This ticket needs more discussion when it gets tackled. Ping me for details!
